env: dev # production
application:
  host: 0.0.0.0
  port: 3000
db:
  name: postgres
  host: postgres
  username: postgres
  password: postgres
  port: 5432
  timezone: Asia/Jakarta
  migration_path: file://migrations/
  max_connections: 10
  min_connections: 5
