services:
  url-shortener:
    container_name: url-shortener
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres
    links:
      - postgres
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
  postgres:
    container_name: postgres
    image: "postgres:16.1-alpine3.19"
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - postgres
    healthcheck:
      test:
        ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 2m
      retries: 10
      start_period: 40s
volumes:
  postgres:
networks:
  postgres:
    name: postgres
