services:
  url-shortener:
    container_name: url-shortener
    build: .
    healthcheck:
      test: ["CMD", "curl", "url-shortener:${APPLICATION_PORT}"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 15s
    restart: always
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      prometheus:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - grafana
      - postgres
      - redis
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-retries: 5
        loki-batch-size: 1000
    ports:
      - 8080:${APPLICATION_PORT}
  postgres:
    container_name: postgres
    image: postgres:16.1-alpine3.19
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - postgres
    healthcheck:
      test:
        ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 3s
  redis:
    container_name: redis
    image: redis/redis-stack:7.2.0-v13
    restart: always
    environment:
      REDIS_ARGS: "--user redis on +@all ~* >redis  --bind 0.0.0.0 --maxmemory-policy allkeys-lru"
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 3s
    networks:
      - redis
    volumes:
      - redis:/data
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  grafana:
    container_name: grafana
    image: grafana/grafana:11.3.0-ubuntu
    volumes:
      - ./observability/grafana/provisioning/datasources.yaml:/etc/grafana/provisioning/datasources/default.yaml
      - ./observability/grafana/provisioning/dashboards.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./observability/grafana/dashboards/node-exporter.json:/var/lib/grafana/dashboards/node-exporter.json
    depends_on:
      - url-shortener
      - prometheus
      - loki
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    networks:
      - grafana
      - postgres
      - url-shortener
  loki:
    container_name: loki
    image: grafana/loki:2.9.2
    ports:
      - 3100:3100
    command: ["-config.file=/etc/loki/loki.yaml", "-config.expand-env=true"]
    volumes:
      - ./observability/loki.yaml:/etc/loki/loki.yaml
    networks:
      - grafana
    env_file: .env
  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus.yaml
      - --enable-feature=exemplar-storage
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
      - --web.enable-remote-write-receiver
    volumes:
      - ./observability/prometheus.yaml:/etc/prometheus.yaml
      - prometheus:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - node-exporter
    networks:
      - grafana
  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    networks:
      - grafana
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.112.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./observability/otel-collector.yaml:/etc/otel-collector.yaml
    expose:
      - 4317
      - 4318
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
    networks:
      - grafana
    depends_on:
      - jaeger
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.62.0
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
    expose:
      - 4317
      - 4318
    networks:
      - grafana
volumes:
  postgres:
    name: postgres
  prometheus:
    name: prometheus
  redis:
    name: redis
networks:
  postgres:
    name: postgres
  grafana:
    name: grafana
  url-shortener:
    name: url-shortener
  redis:
    name: redis
