// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Url struct {
	ID           uuid.UUID `json:"id"`
	Url          string    `json:"url"`
	ShortUrl     string    `json:"short_url"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	VisitedCount int32     `json:"visited_count"`
}
