// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Url struct {
	ID           uuid.UUID
	Url          string
	ShortUrl     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	VisitedCount sql.NullInt32
}
