// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package repository

import (
	"context"
)

const getAllUrls = `-- name: GetAllUrls :many
select id, url, short_url, created_at, updated_at, visited_count from urls
`

func (q *Queries) GetAllUrls(ctx context.Context) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, getAllUrls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.ShortUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VisitedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
